title: Óscar R. Garrucho
author: oskarko
email: oscar.garrucho@gmail.com
description: > # this means to ignore newlines until "show_exerpts:"
  Óscar R. Garrucho personal web
show_excerpts: true # set to true to show excerpts on the homepage

domain: oskarko.github.io       # if you want to force HTTPS, specify the domain without the http at the start, e.g. example.com
url: https://oskarko.github.io  # the base hostname and protocol for your site, e.g. http://example.com
baseurl: /oskarko.github.io/  

sass:
  sass_dir: _sass

permalink: /posts/:title/
texture:
  title: Óscar R. Garrucho
  tagline: Senior iOS developer
  date_format: "%b %-d, %Y"
  style: black
  showNav: false
  showPicker: false

  # generate social links in footer
  social_links:
    dev: oskarko
    twitter: oscarGarrucho
    github:  oskarko
    linkedIn: in/oscar-garrucho
    rss: rss
 


plugins:
  - jekyll-seo-tag
#  - jekyll-feed